---

# Set to 'absent' to undeploy
d_state: present

# Discourse variables
d_hostname: discourse.example.com
d_sitename: Discourse
d_password: SetMe

# PostgreSQL details
d_pg_host: postgres.postgres.svc
d_pg_root_user: postgres
d_pg_root_password: SetMe
d_pg_port_number: 5432
d_discourse_pg_username: bn_discourse
d_discourse_pg_password: bitnami1
d_discourse_pg_name: bitnami_application

# Redis details
d_redis_host: redis-headless.redis.svc
d_redis_port_number: 6379
d_redis_password: SetMe

# SMTP details
d_smtp_host: SetMe
d_smtp_port: 587
d_smtp_user: SetMe
d_smtp_password: SetMe
