---

d_namespace: discourse
d_sa_psp: im-core-unrestricted

d_image_name: bitnami/discourse
d_image_tag: 2.5.0

d_vol_storageclass: ' '
d_vol_size_g: 8

d_node_purpose: application
d_pod_ready_timeout: 600

d_cert_issuer: production

# General variables

wait_for_bind: no
bind_timeout: 240
pod_ready_timeout: 600
