---
name: lint

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# At the GitHub 'organisation' or 'project' level you must have the following
# GitHub 'Repository Secrets' defined (i.e. via 'Settings -> Secrets'): -
#
# (none)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (none)

on:
  push:
  schedule:
  # Build daily at 6:52am...
  - cron: '52 6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r build-requirements.txt
        pip install -r requirements.txt
    - name: Lint
      run: |
        yamllint .
        find . -type f -name '*.yaml.j2' -exec yamllint {} +
        ansible-lint
